name: Deploy Runner to Lab Personal

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6 

      - name: Configura aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::519904985894:role/GitHubActionsRole
          aws-region: us-east-1

      - name: Create S3 Bucket for Terraform State
        run: |
          aws s3api create-bucket --bucket my-terraform-state-bucket --region us-east-1 --create-bucket-configuration LocationConstraint=us-east-1 || echo "Bucket already exists"
          aws s3api put-bucket-versioning --bucket my-terraform-state-bucket --versioning-configuration Status=Enabled
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Init
        run: terraform init -backend-config="bucket=my-terraform-state-bucket" -backend-config="key=terraform.tfstate" -backend-config="region=us-east-1"
        working-directory: ./runner-ephemeral

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./runner-ephemeral

      - name: Terraform Plan
        run: terraform plan -out=tfplan -var-file=../env/lab.tfvars
        working-directory: ./runner-ephemeral

      # Apply Terraform (requires approval for safety)
      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
        working-directory: ./runner-ephemeral